version: "3.9"
services:

  app:
    container_name: as-app
    image: artificial-sapiens
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - as

networks:
  as:
    driver: bridge